import type { SiteContent } from "@/types/content";

/**
 * PLACEHOLDER CONTENT.
 *
 * `varagh.example` is the IANA-reserved placeholder name, used here so the
 * address and the handle read unmistakably as stand-ins and cannot resolve to
 * some real account that would then be associated with a studio that does not
 * exist. They are structurally valid — the pattern is demonstrated — and
 * simply do not lead anywhere.
 *
 * WHAT IS DELIBERATELY ABSENT: a phone number, a WhatsApp number, and a form.
 * The engine this repo comes from led with WhatsApp click-to-chat, which is
 * right for a shop and wrong here — a studio is reached by email. A phone
 * number on this page would be either a real one nobody answers or a row of
 * zeros that makes the demo look unfinished. Two channels, both real-shaped.
 */
const HANDLE = "varagh.example";

export const site: SiteContent = {
  brand: {
    name: "ورق",
    latin: "VARAGH",
    line: "استودیوی طراحی گرافیک — هویت بصری، چاپ و نشر، بسته‌بندی.",
  },

  seo: {
    title: "ورق — استودیوی طراحی گرافیک",
    titleTemplate: "%s — ورق",
    description:
      "ورق یک استودیوی طراحی گرافیک است. شش کار در سه حوزه: هویت بصری، چاپ و نشر، بسته‌بندی.",
    /** Generated by `scripts/generate-og.mjs` — a PNG, because no social
     *  crawler renders an SVG share card. */
    ogImage: {
      src: "/media/og-card.png",
      alt: "نشان ورق روی زمینهٔ مشکی",
      width: 1200,
      height: 630,
    },
  },

  /**
   * Three destinations and no more. Every href is written from the site root
   * so the header works on every page — a bare `#contact` resolves against
   * whatever page the header happens to be rendered on, which is nothing at
   * all outside the homepage. `next/link` applies the deployment base path to
   * a root-relative href, which is also the only form that survives being
   * served from a GitHub Pages project subpath.
   */
  nav: [
    { label: "فهرست کارها", href: "/products/" },
    { label: "آرشیو", href: "/gallery/" },
    { label: "استودیو", href: "/about/" },
  ],

  contact: {
    city: "تهران",
    email: "info@varagh.example",
    instagram: { handle: `@${HANDLE}`, href: `https://instagram.com/${HANDLE}` },
  },

  footer: {
    navHeading: "صفحه‌ها",
    contactHeading: "تماس",
  },

  /**
   * Persian digits, and that is not a contradiction of the Latin-digit rule in
   * `src/lib/digits.ts`. The exception there is scoped to *catalogue marks* —
   * a work's number, an archive code, the year printed in a work's spec table.
   * A copyright line is running Persian prose in a footer, not a mark stamped
   * on a plate, so it follows the ordinary rule.
   */
  copyright: "© ۱۴۰۵ ورق",
};
