/**
 * Open Graph card generator.
 *
 * **No social crawler renders an SVG `og:image`** — Facebook, X, LinkedIn and
 * Telegram all ignore it and fall back to no preview at all. So the share card
 * has to be a raster, and it is the one PNG in the project.
 *
 * It is written here rather than fetched, generated by a service, or produced
 * with an image library, because this project has exactly three runtime
 * dependencies and adding one to draw three rectangles is a bad trade. Node's
 * own `zlib` is all a PNG encoder needs.
 *
 * The card is the mark from `src/app/icon.svg` at card scale: the sheet, the
 * hot band across it, on the ink ground. No gradient, no glow, no vignette —
 * the plates the site actually shows are photographs, but the card is the
 * mark, and the mark is flat.
 *
 * It carries no type. Rendering Persian into a generated raster needs a font
 * pipeline this project does not have, and a Latin-only card for a Persian
 * studio would read worse than a clean mark.
 *
 *   node scripts/generate-og.mjs
 */
import { deflateSync } from "node:zlib";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "public", "media");
mkdirSync(outDir, { recursive: true });

/** Open Graph's expected card size. 1.91:1, which is what every consumer crops to. */
const W = 1200;
const H = 630;

/** Kept in sync with src/app/tokens.css and scripts/generate-media.mjs. */
const MORAKKAB = [0x0a, 0x0a, 0x0a];
const SHANGARF = [0xff, 0x3b, 0x00];
const KAGHAZ = [0xf2, 0xf2, 0xf0];

/* -------------------------------------------------------------------------- */
/*  PNG encoding                                                              */
/* -------------------------------------------------------------------------- */

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length, 0);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body), 0);
  return Buffer.concat([length, body, crc]);
}

/**
 * Truecolour 8-bit PNG from a raw RGB buffer.
 *
 * Every scanline uses filter type 1 (Sub — each byte minus the one three to its
 * left). On a smooth horizontal gradient that leaves a run of near-zeroes, so
 * deflate turns a 2.2 MB raw image into tens of kilobytes. Filter 0 on the same
 * data is several times larger.
 */
function encodePng(width, height, rgb) {
  const stride = width * 3;
  const raw = Buffer.alloc((stride + 1) * height);

  for (let y = 0; y < height; y++) {
    const src = y * stride;
    const dst = y * (stride + 1);
    raw[dst] = 1;
    for (let x = 0; x < stride; x++) {
      const left = x >= 3 ? rgb[src + x - 3] : 0;
      raw[dst + 1 + x] = (rgb[src + x] - left) & 0xff;
    }
  }

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // colour type: truecolour
  // 10–12: compression, filter and interlace methods — all 0, the only values
  // the format defines.

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

/* -------------------------------------------------------------------------- */
/*  The card                                                                  */
/* -------------------------------------------------------------------------- */

const clamp01 = (v) => (v < 0 ? 0 : v > 1 ? 1 : v);
const mix = (a, b, t) => a + (b - a) * t;

/** Smooth 0-to-1 ramp, used only to antialias the rectangle edges. */
function smoothstep(edge0, edge1, x) {
  const t = clamp01((x - edge0) / (edge1 - edge0));
  return t * t * (3 - 2 * t);
}

/** Source-over composite of a straight colour at `alpha` onto `dst`. */
function over(dst, colour, alpha) {
  if (alpha <= 0) return;
  for (let i = 0; i < 3; i++) dst[i] = mix(dst[i], colour[i], alpha);
}

/**
 * Coverage of an axis-aligned rectangle, antialiased across one pixel.
 *
 * A hard edge at 8 bits is the whole point of this card, so nothing here is
 * feathered further than one pixel — and there is no gradient anywhere on it,
 * which is also why the ordered dither the earlier version of this script
 * needed is gone. Dithering exists to break up banding in a wide ramp; there
 * is no ramp left to band.
 */
function rect(x, y, x0, y0, x1, y1) {
  const ax = smoothstep(x0 - 0.5, x0 + 0.5, x) * (1 - smoothstep(x1 - 0.5, x1 + 0.5, x));
  const ay = smoothstep(y0 - 0.5, y0 + 0.5, y) * (1 - smoothstep(y1 - 0.5, y1 + 0.5, y));
  return ax * ay;
}

const rgb = Buffer.alloc(W * H * 3);
const px = [0, 0, 0];

// The mark, from src/app/icon.svg: a 32-unit box scaled up and set at the
// optical centre. Social cards are cropped differently by every consumer, so
// the mark stays well inside the safe area rather than bleeding.
const MARK = { size: 380, cx: 600, cy: 315 };
const scale = MARK.size / 32;
const originX = MARK.cx - MARK.size / 2;
const originY = MARK.cy - MARK.size / 2;
const mx = (u) => originX + u * scale;
const my = (v) => originY + v * scale;

for (let y = 0; y < H; y++) {
  for (let x = 0; x < W; x++) {
    px[0] = MORAKKAB[0];
    px[1] = MORAKKAB[1];
    px[2] = MORAKKAB[2];

    // The sheet.
    over(px, KAGHAZ, rect(x, y, mx(7), my(4), mx(25), my(28)));
    // The band across it.
    over(px, SHANGARF, rect(x, y, mx(7), my(14), mx(25), my(18)));

    const o = (y * W + x) * 3;
    rgb[o] = px[0];
    rgb[o + 1] = px[1];
    rgb[o + 2] = px[2];
  }
}

const file = join(outDir, "og-card.png");
const png = encodePng(W, H, rgb);
writeFileSync(file, png);
console.log(`generated og-card.png  ${W}×${H}  ${(png.length / 1024).toFixed(0)} KB → public/media/`);
